version: "3.6"

services:
  flex-node-adapter:
    container_name: flex-node-adapter
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    restart: always
    ports:
      - 8080:8080
    command: start-dev
